proj = currentProject;
projectRoot = string(proj.RootFolder);

experimentCfg = ares.config.defaultSingleUav();
experimentCfg.sensors.lidar.enabled = false;

manifest = ares.data.createRunManifest( ...
    projectRoot, ...
    "ares_single_uav_top", ...
    "lidar-disabled-single-uav", ...
    experimentCfg);

manifest.groundTruth.condition = "lidar-disabled";
manifest.groundTruth.faultType = "lidar-unavailable";
manifest.groundTruth.faultActive = true;
manifest.groundTruth.faultStartTime_s = 0;

% initializeSingleUav.m consumes this override.
SingleUavConfigOverride = experimentCfg;

safetyChecksPassed = true;
failureIdentifier = "";
failureMessage = "";

try
    run(fullfile( ...
        projectRoot, ...
        "scripts", ...
        "runSingleUav.m"));

catch simulationError
    simulationCompleted = ...
        exist("simOut", "var") && ...
        isa(simOut, "Simulink.SimulationOutput");

    expectedSafetyFailure = ...
        simulationCompleted && ...
        contains(string(simulationError.message), "ARES");

    if ~expectedSafetyFailure
        rethrow(simulationError);
    end

    safetyChecksPassed = false;
    failureIdentifier = string( ...
        simulationError.identifier);
    failureMessage = string( ...
        simulationError.message);

    fprintf("\nExpected experimental safety failure:\n%s\n", ...
        failureMessage);
end

assert(~LidarEnabled, ...
    "LiDAR was not disabled during the experiment.");

manifest.groundTruth.faultEndTime_s = ...
    simOut.tout(end);

manifest.outcome.safetyChecksPassed = ...
    safetyChecksPassed;

manifest.outcome.failureIdentifier = ...
    failureIdentifier;

manifest.outcome.failureMessage = ...
    failureMessage;

manifest.metrics.finalWaypointErrorM = ...
    finalWaypointErrorM;

manifest.metrics.minimumAltitudeM = ...
    minimumAltitudeM;

manifest.metrics.maximumAltitudeM = ...
    maximumAltitudeM;

manifest.metrics.minimumObstacleClearanceM = ...
    minimumObstacleClearanceM;

manifest.metrics.requiredObstacleClearanceM = ...
    requiredObstacleClearanceM;

telemetry = ares.data.extractRawTelemetry( ...
    simOut, ...
    manifest);

manifestPath = ares.data.saveRuntimeManifest( ...
    projectRoot, ...
    manifest);

telemetryPath = ares.data.saveRawTelemetry( ...
    projectRoot, ...
    telemetry);

fprintf("\nLiDAR-disabled run captured.\n");
fprintf("Run ID: %s\n", manifest.runId);
fprintf("Safety checks passed: %d\n", ...
    safetyChecksPassed);
fprintf("Minimum clearance: %.2f m\n", ...
    minimumObstacleClearanceM);
fprintf("Run folder: %s\n", ...
    string(fileparts(telemetryPath)));

% Restore the normal configuration for future runs.
run(fullfile( ...
    projectRoot, ...
    "scripts", ...
    "initializeSingleUav.m"));

assert(LidarEnabled);

disp("PASS: Experimental telemetry saved and nominal mode restored.");