proj = currentProject;
projectRoot = string(proj.RootFolder);

experimentCfg = ares.config.defaultSingleUav();

% The system starts with LiDAR guidance enabled.
experimentCfg.sensors.lidar.enabled = true;
experimentCfg.sensors.lidar.mode = "intermittent";

simulationStopTime = ...
    double(experimentCfg.simulation.stopTime);

%% Random outage configuration

faultConfiguration.randomSeed = 513;
faultConfiguration.numberOfOutages = 3;

faultConfiguration.initialHealthyTime_s = 5;
faultConfiguration.finalHealthyTime_s = 5;

faultConfiguration.minimumOutageDuration_s = 2;
faultConfiguration.maximumOutageDuration_s = 5;

faultConfiguration.minimumRecoveryDuration_s = 4;

[LidarEnableSchedule, outageIntervals_s] = ...
    createRandomLidarSchedule( ...
        simulationStopTime, ...
        faultConfiguration);

fprintf("Generated LiDAR outage intervals:\n");

disp(array2table( ...
    outageIntervals_s, ...
    "VariableNames", ...
    ["StartTime_s", "EndTime_s"]));

%% Create manifest

manifest = ares.data.createRunManifest( ...
    projectRoot, ...
    "ares_single_uav_top", ...
    "intermittent-lidar-single-uav", ...
    experimentCfg);

manifest.groundTruth.condition = ...
    "intermittent-lidar";

manifest.groundTruth.faultType = ...
    "intermittent-lidar-unavailable";

manifest.groundTruth.faultActive = true;

manifest.groundTruth.faultStartTime_s = ...
    outageIntervals_s(1, 1);

manifest.groundTruth.faultEndTime_s = ...
    outageIntervals_s(end, 2);

manifest.groundTruth.outageIntervals_s = ...
    outageIntervals_s;

manifest.groundTruth.randomSeed = ...
    faultConfiguration.randomSeed;

manifest.groundTruth.scheduleTime_s = ...
    LidarEnableSchedule.Time;

manifest.groundTruth.scheduleEnabled = ...
    logical(LidarEnableSchedule.Data);

%% Supply one-time overrides

SingleUavConfigOverride = experimentCfg;

SingleUavLidarScheduleOverride = ...
    LidarEnableSchedule;

safetyChecksPassed = true;
failureIdentifier = "";
failureMessage = "";

try
    try
        run(fullfile( ...
            projectRoot, ...
            "scripts", ...
            "runSingleUav.m"));

    catch simulationError
        simulationCompleted = ...
            exist("simOut", "var") && ...
            isa(simOut, ...
                "Simulink.SimulationOutput");

        expectedSafetyFailure = ...
            simulationCompleted && ...
            contains( ...
                string(simulationError.message), ...
                "ARES");

        if ~expectedSafetyFailure
            rethrow(simulationError);
        end

        safetyChecksPassed = false;

        failureIdentifier = ...
            string(simulationError.identifier);

        failureMessage = ...
            string(simulationError.message);

        fprintf( ...
            "\nExpected experimental safety failure:\n%s\n", ...
            failureMessage);
    end

    %% Verify that the schedule reached Simulink

    enableElement = ...
        simOut.logsout.getElement( ...
            "lidar_enabled");

    assert(~isempty(enableElement), ...
        "ARES:LidarScheduleNotLogged", ...
        "The lidar_enabled signal was not logged.");

    observedEnableValues = logical( ...
        squeeze(enableElement.Values.Data));

    assert(any(~observedEnableValues), ...
        "ARES:LidarOutageNotObserved", ...
        "No LiDAR-disabled samples were observed.");

    assert(any(observedEnableValues), ...
        "ARES:LidarRecoveryNotObserved", ...
        "LiDAR never returned to its enabled state.");

    %% Record outcome

    manifest.outcome.safetyChecksPassed = ...
        safetyChecksPassed;

    manifest.outcome.failureIdentifier = ...
        failureIdentifier;

    manifest.outcome.failureMessage = ...
        failureMessage;

    manifest.outcome.lidarOutageObserved = ...
        any(~observedEnableValues);

    manifest.outcome.lidarRecoveryObserved = ...
        any(observedEnableValues);

    manifest.metrics.finalWaypointErrorM = ...
        finalWaypointErrorM;

    manifest.metrics.minimumAltitudeM = ...
        minimumAltitudeM;

    manifest.metrics.maximumAltitudeM = ...
        maximumAltitudeM;

    manifest.metrics.minimumObstacleClearanceM = ...
        minimumObstacleClearanceM;

    manifest.metrics.requiredObstacleClearanceM = ...
        requiredObstacleClearanceM;

    %% Save run

    telemetry = ares.data.extractRawTelemetry( ...
        simOut, ...
        manifest);

    manifestPath = ...
        ares.data.saveRuntimeManifest( ...
            projectRoot, ...
            manifest);

    telemetryPath = ...
        ares.data.saveRawTelemetry( ...
            projectRoot, ...
            telemetry);

    fprintf("\nIntermittent-LiDAR run captured.\n");
    fprintf("Run ID: %s\n", manifest.runId);
    fprintf("Random seed: %d\n", ...
        faultConfiguration.randomSeed);
    fprintf("Outage count: %d\n", ...
        size(outageIntervals_s, 1));
    fprintf("Safety checks passed: %d\n", ...
        safetyChecksPassed);
    fprintf("Minimum clearance: %.2f m\n", ...
        minimumObstacleClearanceM);
    fprintf("Run folder: %s\n", ...
        string(fileparts(telemetryPath)));

catch experimentError
    % Restore ordinary initialization even after an unexpected failure.
    run(fullfile( ...
        projectRoot, ...
        "scripts", ...
        "initializeSingleUav.m"));

    rethrow(experimentError);
end

%% Restore nominal mode

run(fullfile( ...
    projectRoot, ...
    "scripts", ...
    "initializeSingleUav.m"));

assert(LidarEnabled);

assert(all( ...
    logical(LidarEnableSchedule.Data)));

disp("PASS: Intermittent fault captured and nominal mode restored.");

%% Local schedule generator

function [schedule, intervals] = ...
        createRandomLidarSchedule(stopTime, faultCfg)

    outageCount = ...
        faultCfg.numberOfOutages;

    minimumRequiredTime = ...
        faultCfg.initialHealthyTime_s ...
        + faultCfg.finalHealthyTime_s ...
        + outageCount ...
            * faultCfg.minimumOutageDuration_s ...
        + max(outageCount - 1, 0) ...
            * faultCfg.minimumRecoveryDuration_s;

    assert(stopTime >= minimumRequiredTime, ...
        "ARES:InsufficientFaultScheduleTime", ...
        ["Simulation is too short for the requested number " ...
         "of LiDAR outages."]);

    % Local random stream avoids changing MATLAB's global RNG.
    randomStream = RandStream( ...
        "mt19937ar", ...
        "Seed", ...
        faultCfg.randomSeed);

    intervals = zeros(outageCount, 2);

    earliestStartTime = ...
        faultCfg.initialHealthyTime_s;

    for outageIndex = 1:outageCount

        remainingOutages = ...
            outageCount - outageIndex;

        remainingMinimumTime = ...
            faultCfg.finalHealthyTime_s ...
            + remainingOutages ...
                * faultCfg.minimumOutageDuration_s ...
            + remainingOutages ...
                * faultCfg.minimumRecoveryDuration_s;

        latestStartTime = ...
            stopTime ...
            - faultCfg.minimumOutageDuration_s ...
            - remainingMinimumTime;

        startTime = ...
            earliestStartTime ...
            + rand(randomStream) ...
                * (latestStartTime ...
                    - earliestStartTime);

        maximumAllowedDuration = min( ...
            faultCfg.maximumOutageDuration_s, ...
            stopTime ...
                - startTime ...
                - remainingMinimumTime);

        duration = ...
            faultCfg.minimumOutageDuration_s ...
            + rand(randomStream) ...
                * (maximumAllowedDuration ...
                    - faultCfg.minimumOutageDuration_s);

        endTime = startTime + duration;

        intervals(outageIndex, :) = ...
            [startTime, endTime];

        earliestStartTime = ...
            endTime ...
            + faultCfg.minimumRecoveryDuration_s;
    end

    transitionTimes = [
        0
        reshape(intervals.', [], 1)
        stopTime
    ];

    % Starts enabled, alternates off/on, and ends enabled.
    availabilityValues = [
        1
        repmat([0; 1], outageCount, 1)
        1
    ];

    schedule = timeseries( ...
        availabilityValues, ...
        transitionTimes);
    % schedule.DataInfo.Interpolation = tsdata.interpolation('zoh');

    schedule.Name = "lidar_enabled";
end